version: '3.8'

services:

  postgres:
    image: postgres:17-alpine
    container_name: system_oficina_db
    environment:
      POSTGRES_DB: system_oficina
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/distribuidora_mvp.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - system_oficina_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: system_oficina_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/system_oficina
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - system_oficina_network

volumes:
  postgres_data:

networks:
  system_oficina_network:
    driver: bridge