spring.application.name=system_oficina
#=================================
# Configurações do banco de dados
#=================================
spring.datasource.url=jdbc:postgresql://localhost:5432/system_oficina
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#=================================
# CONFIGURAÇÃO DO JPA/HIBERNATE
# ================================
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================================
# CONFIGURAÇÃO DO SERVIDOR
# ================================
server.port=8080