spring.application.name=system_oficina

spring.datasource.url=jdbc:postgresql://localhost:5432/system_oficina
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080


jwt.secret=sua_chave_secreta_muito_longa_e_segura_aqui_12345
jwt.expiration=86400000